name.en = "Cherubikon"
name.gr = "Xερουβικόν"
name.ro = "Heruvicul"

[variants.weekdays]
name.en = "Cherubikon of the week days"
name.gr = "Xερουβικόν εβδομάδος"
name.ro = "Heruvicul săptămânal"

[[part_of]]
text = "@texts/divine-liturgy"
