name.ro = "Heruvic Saptamanal, glas 1, de Petru Lampadarie"
name.gr = "Χερουβικό Πέτρου Λαμπαδαρίου, Ήχος Α΄"

text = "@texts/cherubikon"
author = "@people/petros-peloponnesios"
contribution = "composed"

performances = []
publications = []

category = "@taxonomy/papadic"
tags = []
