name.ro = "Sfinte Dumnezeule, glas 2, Traditional, Tradus de Schim. Nectarie"

text = "@texts/trisagion"
author = "@people/nectarie-protopsaltul"
contribution = "translated@trisaghion-glas2-traditional"

performances = []
publications = []

category = "@taxonomies/papadic"
tags = []

[musical]
mode = 2
base = "DI"
modulations = []
