name.ro = "Sfinte Dumnezeule, glas 2, Traditional, Tradus de Schim. Nectarie"

text = "@texts/trisagion"
author = "@people/nectarie-protopsaltul"
contribution = "translated@compositions/trisaghion-glas2-traditional"

performances = []
publications = []

category = "@taxonomy/papadic"
tags = []
